/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PointsRouteImport } from './routes/points'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunRunIdRouteImport } from './routes/run.$runId'
import { Route as PlayerPlayerIdRouteImport } from './routes/player.$playerId'

const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PointsRoute = PointsRouteImport.update({
  id: '/points',
  path: '/points',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunRunIdRoute = RunRunIdRouteImport.update({
  id: '/run/$runId',
  path: '/run/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerPlayerIdRoute = PlayerPlayerIdRouteImport.update({
  id: '/player/$playerId',
  path: '/player/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/downloads': typeof DownloadsRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/live': typeof LiveRoute
  '/points': typeof PointsRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/submit': typeof SubmitRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
  '/run/$runId': typeof RunRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/downloads': typeof DownloadsRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/live': typeof LiveRoute
  '/points': typeof PointsRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/submit': typeof SubmitRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
  '/run/$runId': typeof RunRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/downloads': typeof DownloadsRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/live': typeof LiveRoute
  '/points': typeof PointsRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/submit': typeof SubmitRoute
  '/player/$playerId': typeof PlayerPlayerIdRoute
  '/run/$runId': typeof RunRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/downloads'
    | '/leaderboards'
    | '/live'
    | '/points'
    | '/settings'
    | '/stats'
    | '/submit'
    | '/player/$playerId'
    | '/run/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/admin'
    | '/downloads'
    | '/leaderboards'
    | '/live'
    | '/points'
    | '/settings'
    | '/stats'
    | '/submit'
    | '/player/$playerId'
    | '/run/$runId'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/downloads'
    | '/leaderboards'
    | '/live'
    | '/points'
    | '/settings'
    | '/stats'
    | '/submit'
    | '/player/$playerId'
    | '/run/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRoute
  DownloadsRoute: typeof DownloadsRoute
  LeaderboardsRoute: typeof LeaderboardsRoute
  LiveRoute: typeof LiveRoute
  PointsRoute: typeof PointsRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  SubmitRoute: typeof SubmitRoute
  PlayerPlayerIdRoute: typeof PlayerPlayerIdRoute
  RunRunIdRoute: typeof RunRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/points': {
      id: '/points'
      path: '/points'
      fullPath: '/points'
      preLoaderRoute: typeof PointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run/$runId': {
      id: '/run/$runId'
      path: '/run/$runId'
      fullPath: '/run/$runId'
      preLoaderRoute: typeof RunRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$playerId': {
      id: '/player/$playerId'
      path: '/player/$playerId'
      fullPath: '/player/$playerId'
      preLoaderRoute: typeof PlayerPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRoute,
  DownloadsRoute: DownloadsRoute,
  LeaderboardsRoute: LeaderboardsRoute,
  LiveRoute: LiveRoute,
  PointsRoute: PointsRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  SubmitRoute: SubmitRoute,
  PlayerPlayerIdRoute: PlayerPlayerIdRoute,
  RunRunIdRoute: RunRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
